---
- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Install docker
      shell: curl https://get.docker.com | sh

    - name: Add remote "hidemire" user to "docker" group
      user:
        name: hidemire
        groups: docker
        append: yes

    - name: Install or upgrade docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: "a+x"
#   - name: Install docker packages
#     remote_user: ubuntu
#     apt:
#       name: "{{ item }}"
#       state: present
#       update_cache: yes
#     with_items:
#       - apt-transport-https
#       - ca-certificates
#       - curl
#       - software-properties-common
#     tags:
#       - docker
#   - name: Add Docker s official GPG key
#     remote_user: ubuntu
#     apt_key:
#       url: https://download.docker.com/linux/ubuntu/gpg
#       state: present
#     tags:
#       - docker
#   - name: Set up the stable repository
#     remote_user: ubuntu
#     apt_repository:
#       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
#       state: present
#       update_cache: yes
#     tags:
#       - docker
#   - name: Update apt packages
#     remote_user: ubuntu
#     apt:
#       update_cache: yes
#     tags:
#       - docker
#   - name: Install docker
#     remote_user: ubuntu
#     apt:
#       name: docker-ce
#       state: present
#       update_cache: yes
#     #notify: Start docker on boot
#     tags:
#       - docker
#   - name: Add remote "ubuntu" user to "docker" group
#     user:
#       name: "hidemire"
#       group: "docker"
#       append: yes
#     tags:
#       - docker
#   - name: Install docker-compose
#     remote_user: ubuntu
#     get_url:
#       url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
#       dest: /usr/local/bin/docker-compose
#       mode: 'u+x,g+x'
